"""
Hierarchical Agent Orchestrator - 1+3+1 Architecture

Implements hierarchical planning with parallel worker execution:
1. Architect creates reading plan
2. 3 Specialists work in parallel (Context Hunter, Math Specialist, Data Auditor)
3. Editor assembles final report

This approach provides:
- Better division of labor
- Parallel execution for faster processing
- More focused, higher quality analysis
"""

import json
import re
import asyncio
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.panel import Panel

from config import LLMConfig
from llm import LLMClientFactory

from .hierarchical_prompts import (
    ARCHITECT_SYSTEM, ARCHITECT_PROMPT,
    CONTEXT_HUNTER_SYSTEM, CONTEXT_HUNTER_PROMPT,
    MATH_SPECIALIST_SYSTEM, MATH_SPECIALIST_PROMPT,
    DATA_AUDITOR_SYSTEM, DATA_AUDITOR_PROMPT,
    EDITOR_SYSTEM, EDITOR_PROMPT,
    EDITOR_CHINESE_SYSTEM, EDITOR_CHINESE_PROMPT,
)

console = Console()


@dataclass
class ReadingPlan:
    """Reading plan generated by Architect"""
    paper_summary: str = ""
    domain: str = ""
    context_hunter_task: Dict = field(default_factory=dict)
    math_specialist_task: Dict = field(default_factory=dict)
    data_auditor_task: Dict = field(default_factory=dict)
    raw_json: str = ""


@dataclass 
class SpecialistReport:
    """Report from a specialist agent"""
    agent_name: str
    content: str
    success: bool = True
    error: Optional[str] = None


@dataclass
class VariableTracking:
    """Variable tracking information extracted from math report"""
    variables: List[Dict] = field(default_factory=list)  # List of variable definitions
    dependency_graph: str = ""  # Text representation of dependency graph
    raw_section: str = ""  # Raw markdown section


@dataclass
class ReproductionChecklist:
    """Reproduction checklist extracted from experiment report"""
    datasets: List[Dict] = field(default_factory=list)  # Dataset info
    hyperparameters: List[Dict] = field(default_factory=list)  # Hyperparameter settings
    hardware: List[Dict] = field(default_factory=list)  # Hardware requirements
    code_availability: Dict = field(default_factory=dict)  # Code/model availability
    risk_assessment: List[Dict] = field(default_factory=list)  # Risk factors
    raw_section: str = ""  # Raw markdown section


@dataclass
class HierarchicalAnalysisResult:
    """Complete analysis result from hierarchical pipeline"""
    title: str = ""
    domain: str = ""
    reading_plan: Optional[ReadingPlan] = None
    context_report: str = ""
    math_report: str = ""
    experiment_report: str = ""
    final_report: str = ""
    final_report_chinese: str = ""  # Chinese version
    figure_suggestions: Dict[str, str] = field(default_factory=dict)
    # New fields for P0 features
    variable_tracking: Optional[VariableTracking] = None
    reproduction_checklist: Optional[ReproductionChecklist] = None


class HierarchicalOrchestrator:
    """
    Orchestrates the 1+3+1 hierarchical agent pipeline.
    
    Flow:
    1. Architect analyzes paper structure → Reading Plan
    2. Specialists execute in parallel:
       - Context Hunter → Background/Motivation
       - Math Specialist → Methods/Derivations
       - Data Auditor → Experiments/Results
    3. Editor assembles → Final Report
    """
    
    def __init__(
        self,
        provider: str = "deepseek",
        model: str = "deepseek-chat",
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        temperature: float = 0.3,
        max_tokens: int = 8192,
        max_workers: int = 3,  # For parallel execution
        verbose: bool = False,  # Enable detailed logging
    ):
        """Initialize the hierarchical orchestrator."""
        self.provider = provider
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.max_workers = max_workers
        self.verbose = verbose  # Store verbose flag
        
        # Create LLM config and factory
        llm_config = LLMConfig(
            provider=provider,
            model=model,
            api_key=api_key,
            base_url=base_url,
            temperature=temperature,
            max_tokens=max_tokens
        )
        
        self.factory = LLMClientFactory(llm_config)
        
        # Store progress callback (set in analyze_paper)
        self.progress_callback: Optional[Any] = None
        
        console.print(Panel.fit(
            f"[bold blue]Hierarchical Orchestrator[/bold blue]\n"
            f"[dim]Provider: {provider} | Model: {model}[/dim]\n"
            f"[dim]Max parallel workers: {max_workers} | Verbose: {verbose}[/dim]",
            border_style="blue"
        ))
    
    def analyze_paper(
        self,
        content: str,
        title: str = "",
        headers: List[str] = None,
        abstract: str = "",
        total_pages: int = 0,
        images: List[Any] = None,
        figure_index_path: Optional[Path] = None,  # NEW: Path to figure_index.json
        progress_callback = None,  # NEW: Callback for progress updates
        language: str = "en"  # NEW: Output language
    ) -> HierarchicalAnalysisResult:
        """
        Execute the complete hierarchical analysis pipeline.
        
        Args:
            content: Full paper markdown content
            title: Paper title
            headers: List of section headers
            abstract: Paper abstract
            total_pages: Total page count
            images: List of extracted images
            figure_index_path: Path to figure_index.json for detailed figure info
            progress_callback: Optional callback for WebSocket progress updates
            language: Output language ("en" or "zh")
            
        Returns:
            HierarchicalAnalysisResult with complete analysis
        """
        result = HierarchicalAnalysisResult(title=title)
        
        # Store progress callback for use in _call_llm
        self.progress_callback = progress_callback
        
        # Extract abstract if not provided
        if not abstract:
            abstract = self._extract_abstract(content)
        
        # Extract headers if not provided
        if not headers:
            headers = self._extract_headers(content)
        
        console.print("\n[bold]═══ Phase 1: Architect Planning ═══[/bold]")
        
        # Emit progress: Architect started
        if progress_callback:
            progress_callback.architect_started()
        
        # Step 1: Architect creates reading plan
        result.reading_plan = self._run_architect(
            title=title,
            abstract=abstract,
            headers=headers,
            total_pages=total_pages,
            progress_callback=progress_callback
        )
        result.domain = result.reading_plan.domain
        
        console.print(f"[green]✓[/green] Domain identified: {result.domain}")
        console.print(f"[green]✓[/green] Reading plan created")
        
        # Emit progress: Architect completed
        if progress_callback:
            progress_callback.architect_completed(result.domain)
            if hasattr(progress_callback, 'report_architect_plan'):
                 progress_callback.report_architect_plan(result.reading_plan)
        
        console.print("\n[bold]═══ Phase 2: Specialist Analysis (Parallel) ═══[/bold]")
        
        # Emit progress: Specialists started
        if progress_callback:
            progress_callback.specialist_started("context_hunter")
            progress_callback.specialist_started("math_specialist")
            progress_callback.specialist_started("data_auditor")
        
        # Step 2-3: Run specialists and editors in parallel using single executor
        # Create single ThreadPoolExecutor for all parallel work
        with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            # Step 2: Run specialists in parallel
            specialist_reports = self._run_specialists_parallel(
                content=content,
                reading_plan=result.reading_plan,
                progress_callback=progress_callback,
                executor=executor,
                language=language
            )
            
            result.context_report = specialist_reports.get("context_hunter", "")
            result.math_report = specialist_reports.get("math_specialist", "")
            result.experiment_report = specialist_reports.get("data_auditor", "")
            
            # Extract P0 features: Variable Tracking and Reproduction Checklist
            result.variable_tracking = self._extract_variable_tracking(result.math_report)
            result.reproduction_checklist = self._extract_reproduction_checklist(result.experiment_report)
            
            # Emit progress: Specialists completed
            if progress_callback:
                progress_callback.specialist_completed("context_hunter")
                progress_callback.specialist_completed("math_specialist")
                progress_callback.specialist_completed("data_auditor")
            
            console.print("\n[bold]═══ Phase 3: Editor Assembly (Single Language) ═══[/bold]")
            
            # Emit progress: Editors started
            if progress_callback:
                if language == 'en':
                    progress_callback.editor_started("english")
                else:
                    progress_callback.editor_started("chinese")
            
            # Step 3: Editors assemble final reports in parallel
            # Load figure index for detailed figure information
            available_figures = self._format_figure_list_from_index(figure_index_path) if figure_index_path else self._format_figure_list(images)
            
            # Run English and Chinese editors in parallel (reuse same executor)
            editor_reports = self._run_editors_parallel(
                context_report=result.context_report,
                math_report=result.math_report,
                experiment_report=result.experiment_report,
                available_figures=available_figures,
                title=title,
                progress_callback=progress_callback,
                executor=executor,
                language=language
            )
        
        if language == 'en':
            result.final_report = editor_reports.get("english", "")
            # Extract figure suggestions from English report
            result.figure_suggestions = self._extract_figure_suggestions(result.final_report)
        else:
            result.final_report_chinese = editor_reports.get("chinese", "")
            # Extract figure suggestions from Chinese report
            result.figure_suggestions = self._extract_figure_suggestions(result.final_report_chinese)
        
        # Emit progress: Editors completed
        if progress_callback:
            if language == 'en':
                progress_callback.editor_completed("english", len(result.final_report))
            else:
                progress_callback.editor_completed("chinese", len(result.final_report_chinese))
        
        if language == 'en':
            console.print(f"[green]✓[/green] English report assembled ({len(result.final_report):,} chars)")
        else:
            console.print(f"[green]✓[/green] Chinese report assembled ({len(result.final_report_chinese):,} chars)")
        
        return result
    
    def _call_llm(
        self,
        system: str,
        user: str,
        temperature: Optional[float] = None,
        max_tokens: Optional[int] = None,
        agent_name: str = "LLM",
        agent_key: Optional[str] = None,
        phase: str = "analysis",
        stream: bool = False
    ) -> str:
        """
        Make an LLM API call using unified factory with progress callbacks.
        
        Args:
            system: System prompt
            user: User prompt
            temperature: Override temperature
            max_tokens: Override max_tokens
            agent_name: Human-readable agent name for logging
            agent_key: Agent key for progress events (must match frontend data-agent values)
            phase: Progress phase ("analysis", "assembly", etc.)
        """
        # Map agent_name to agent_key if not provided
        if agent_key is None:
            agent_key_map = {
                "Architect": "architect",
                "context_hunter": "context_hunter",
                "math_specialist": "math_specialist",
                "data_auditor": "data_auditor",
                "Editor_english": "editor_english",
                "Editor_chinese": "editor_chinese",
            }
            agent_key = agent_key_map.get(agent_name, agent_name.lower().replace(" ", "_"))
        
        # Verbose logging: show partial input
        if self.verbose:
            console.print(f"\n[dim]─── {agent_name} Input ───[/dim]")
            console.print(f"[dim]System ({len(system)} chars):[/dim] {system[:500]}...")
            console.print(f"[dim]User ({len(user)} chars):[/dim] {user[:800]}...")
        
        # Use factory for unified LLM call with retry/backoff and progress
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user}
        ]
        
        result = self.factory.chat_completions(
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
            progress_callback=self.progress_callback,
            agent_name=agent_name,
            phase=phase,
            agent_key=agent_key,
            stream=stream
        )
        
        # Verbose logging: show partial output
        if self.verbose:
            console.print(f"[dim]─── {agent_name} Output ({len(result)} chars) ───[/dim]")
            console.print(f"[dim]{result[:800]}...[/dim]")
        
        return result
    
    def _run_architect(
        self,
        title: str,
        abstract: str,
        headers: List[str],
        total_pages: int,
        progress_callback: Optional[Any] = None
    ) -> ReadingPlan:
        """Run the Architect agent to create reading plan."""
        prompt = ARCHITECT_PROMPT.format(
            title=title,
            abstract=abstract[:4000],
            headers="\n".join(f"- {h}" for h in headers),
            total_pages=total_pages
        )
        
        response = self._call_llm(
            ARCHITECT_SYSTEM, 
            prompt, 
            temperature=0.2, 
            agent_name="Architect",
            agent_key="architect",
            phase="analysis"
        )
        response = self._clean_llm_response(response)
        
        # Parse JSON from response
        plan = self._parse_reading_plan(response)
        plan.raw_json = response
        
        return plan
    
    def _clean_llm_response(self, text: str) -> str:
        """Strip markdown code blocks if present."""
        text = text.strip()
        if text.startswith("```markdown"):
            text = text.replace("```markdown", "", 1)
            if text.endswith("```"):
                text = text[:-3]
        elif text.startswith("```"):
            text = text.replace("```", "", 1)
            if text.endswith("```"):
                text = text[:-3]
        return text.strip()
    
    def _parse_reading_plan(self, response: str) -> ReadingPlan:
        """Parse reading plan JSON from Architect response."""
        plan = ReadingPlan()
        
        # Extract JSON block
        json_match = re.search(r'```json\s*(.*?)```', response, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            # Try to find raw JSON
            json_match = re.search(r'\{[\s\S]*\}', response)
            if json_match:
                json_str = json_match.group(0)
            else:
                console.print("[yellow]⚠ Could not parse reading plan JSON[/yellow]")
                return plan
        
        # Fix common JSON issues from LLM output
        json_str = self._fix_json_string(json_str)
        
        try:
            data = json.loads(json_str)
            plan.paper_summary = data.get("paper_summary", "")
            plan.domain = data.get("domain", "")
            plan.context_hunter_task = data.get("context_hunter_task", {})
            plan.math_specialist_task = data.get("math_specialist_task", {})
            plan.data_auditor_task = data.get("data_auditor_task", {})
        except json.JSONDecodeError as e:
            console.print(f"[yellow]⚠ JSON parse error: {e}[/yellow]")
            console.print("[yellow]  Attempting regex fallback extraction...[/yellow]")
            
            # Fallback: extract fields with regex
            # Domain
            domain_match = re.search(r'"domain"\s*:\s*"([^"]+)"', response)
            if domain_match:
                plan.domain = domain_match.group(1)
            
            # Paper summary
            summary_match = re.search(r'"paper_summary"\s*:\s*"([^"]+)"', response)
            if summary_match:
                plan.paper_summary = summary_match.group(1)
            
            # Extract sections for specialists (look for "sections" arrays)
            sections_pattern = r'"sections"\s*:\s*\[([^\]]+)\]'
            sections_matches = re.findall(sections_pattern, response)
            
            # Default sections for each specialist
            default_sections = {
                "context_hunter": ["Introduction", "Related Work", "Background"],
                "math_specialist": ["Method", "Approach", "Methodology", "Model"],
                "data_auditor": ["Experiments", "Results", "Evaluation", "Analysis", "Introduction", "Conclusion", "Abstract"]
            }
            
            plan.context_hunter_task = {"sections": default_sections["context_hunter"]}
            plan.math_specialist_task = {"sections": default_sections["math_specialist"]}
            plan.data_auditor_task = {"sections": default_sections["data_auditor"]}
            
            console.print(f"[green]✓[/green] Fallback: domain='{plan.domain}', using default sections")
        
        return plan
    
    def _fix_json_string(self, json_str: str) -> str:
        """Fix common JSON issues from LLM output."""
        # Remove trailing commas before } or ]
        json_str = re.sub(r',\s*([\}\]])', r'\1', json_str)
        
        # Replace single quotes with double quotes (careful with apostrophes)
        # Only replace single quotes that are likely JSON delimiters
        json_str = re.sub(r"(\s)'([^']+)'(\s*[,:}\]])", r'\1"\2"\3', json_str)
        
        # Fix unquoted keys
        json_str = re.sub(r'(\{|,)\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*:', r'\1"\2":', json_str)
        
        return json_str
    
    def _run_specialists_parallel(
        self,
        content: str,
        reading_plan: ReadingPlan,
        progress_callback: Optional[Any] = None,
        executor: Optional[ThreadPoolExecutor] = None,
        language: str = "en"
    ) -> Dict[str, str]:
        """Run all three specialists in parallel."""
        from .hierarchical_prompts import LANG_INSTRUCTION_EN, LANG_INSTRUCTION_ZH
        
        reports = {}
        
        lang_instruction = LANG_INSTRUCTION_ZH if language == 'zh' else LANG_INSTRUCTION_EN
        
        # Define specialist tasks
        specialists = [
            ("context_hunter", CONTEXT_HUNTER_SYSTEM, CONTEXT_HUNTER_PROMPT + lang_instruction, 
             reading_plan.context_hunter_task, self._extract_sections(content, 
                reading_plan.context_hunter_task.get("sections", ["Introduction", "Related Work"]))),
            
            ("math_specialist", MATH_SPECIALIST_SYSTEM, MATH_SPECIALIST_PROMPT + lang_instruction,
             reading_plan.math_specialist_task, self._extract_sections(content,
                reading_plan.math_specialist_task.get("sections", ["Method", "Approach"]))),
            
            ("data_auditor", DATA_AUDITOR_SYSTEM, DATA_AUDITOR_PROMPT + lang_instruction,
             reading_plan.data_auditor_task, self._extract_sections(content,
                reading_plan.data_auditor_task.get("sections", ["Experiments", "Results"]))),
        ]
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            console=console
        ) as progress:
            
            # Create progress tasks
            task_ids = {}
            for name, _, _, _, _ in specialists:
                task_ids[name] = progress.add_task(f"[cyan]{name}[/cyan]", total=100)
            
            # Execute in parallel (use provided executor or create new one)
            executor_context = executor if executor else ThreadPoolExecutor(max_workers=self.max_workers)
            should_close_executor = executor is None
            
            try:
                if should_close_executor:
                    executor_context = executor_context.__enter__()
                
                futures = {}
                
                for name, system, prompt_template, task_assignment, section_content in specialists:
                    if self.verbose:
                        console.print(f"[dim]  {name} section_content length: {len(section_content)}[/dim]")
                    prompt = prompt_template.format(
                        task_assignment=json.dumps(task_assignment, indent=2),
                        content=section_content  # No truncation for full context
                    )
                    
                    future = executor_context.submit(
                        self._call_llm,
                        system,
                        prompt,
                        None,  # temperature (use default)
                        None,  # max_tokens (use default)
                        name,  # agent_name for verbose logging
                        name,  # agent_key (matches frontend data-agent)
                        "analysis",  # phase
                        True  # stream
                    )
                    futures[future] = name
                
                # Collect results
                for future in as_completed(futures):
                    name = futures[future]
                    try:
                        raw_result = future.result()
                        reports[name] = self._clean_llm_response(raw_result)
                        progress.update(task_ids[name], completed=100)
                        console.print(f"[green]✓[/green] {name} completed")
                    except Exception as e:
                        reports[name] = f"Error: {e}"
                        console.print(f"[red]✗[/red] {name} failed: {e}")
            finally:
                if should_close_executor:
                    executor_context.__exit__(None, None, None)
        
        return reports
    
    def _run_editors_parallel(
        self,
        context_report: str,
        math_report: str,
        experiment_report: str,
        available_figures: str,
        title: str,
        progress_callback: Optional[Any] = None,
        executor: Optional[ThreadPoolExecutor] = None,
        language: str = "en"
    ) -> Dict[str, str]:
        """Run the requested editor (English or Chinese)."""
        reports = {}
        
        # Define editor tasks based on language
        editors = []
        if language == 'en':
            editors.append(("english", "editor_english", EDITOR_SYSTEM, EDITOR_PROMPT))
        elif language == 'zh':
            editors.append(("chinese", "editor_chinese", EDITOR_CHINESE_SYSTEM, EDITOR_CHINESE_PROMPT))
        else:
            # Fallback to English
            editors.append(("english", "editor_english", EDITOR_SYSTEM, EDITOR_PROMPT))
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            console=console,
            transient=True
        ) as progress:
            
            task_ids = {}
            for name, _, _, _ in editors:
                task_ids[name] = progress.add_task(f"Editor ({name}) assembling...", total=100)
            
            # Use provided executor or create new one
            executor_context = executor if executor else ThreadPoolExecutor(max_workers=min(2, self.max_workers))
            should_close_executor = executor is None
            
            try:
                if should_close_executor:
                    executor_context = executor_context.__enter__()
                
                futures = {}
                
                for name, agent_key, system, prompt_template in editors:
                    prompt = prompt_template.format(
                        title=title,
                        context_report=context_report,
                        math_report=math_report,
                        experiment_report=experiment_report,
                        available_figures=available_figures
                    )
                    
                    future = executor_context.submit(
                        self._call_llm,
                        system,
                        prompt,
                        None,  # temperature (use default)
                        None,  # max_tokens (use default)
                        f"Editor ({name})",  # agent_name
                        agent_key,  # agent_key (matches frontend data-agent)
                        "assembly"  # phase
                    )
                    futures[future] = name
                
                for future in as_completed(futures):
                    name = futures[future]
                    try:
                        raw_result = future.result()
                        cleaned = self._clean_llm_response(raw_result)
                        
                        # Add title if not present
                        if title:
                            if name == "english" and not cleaned.startswith(f"# {title}"):
                                cleaned = f"# 📄 {title}\n\n{cleaned}"
                            elif name == "chinese" and not cleaned.startswith(f"# {title}"):
                                cleaned = f"# 📄 {title}\n\n{cleaned}"
                        
                        reports[name] = cleaned
                        progress.update(task_ids[name], completed=100)
                        console.print(f"[green]✓[/green] Editor ({name}) completed")
                    except Exception as e:
                        reports[name] = f"Error: {e}"
                        console.print(f"[red]✗[/red] Editor ({name}) failed: {e}")
            finally:
                if should_close_executor:
                    executor_context.__exit__(None, None, None)
        
        return reports
    
    def _extract_abstract(self, content: str) -> str:
        """Extract abstract from paper content."""
        patterns = [
            r'(?:^|\n)#+\s*abstract\s*\n(.*?)(?=\n#|\Z)',
            r'(?:^|\n)abstract[:\s]*\n(.*?)(?=\n(?:introduction|1\.|#)|\Z)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, content, re.IGNORECASE | re.DOTALL)
            if match:
                return match.group(1).strip()[:1500]
        
        # Fallback: first 500 chars
        return content[:500]
    
    def _extract_headers(self, content: str) -> List[str]:
        """Extract section headers from content."""
        headers = []
        
        # Markdown headers
        for match in re.finditer(r'^#{1,3}\s+(.+)$', content, re.MULTILINE):
            headers.append(match.group(1).strip())
        
        # Numbered sections
        for match in re.finditer(r'^(\d+\.?\s+[A-Z][^.\n]+)', content, re.MULTILINE):
            headers.append(match.group(1).strip())
        
        return headers[:20]  # Limit
    
    def _extract_sections(
        self,
        content: str,
        section_names: List[str]
    ) -> str:
        """
        Extract specific sections from content.
        Uses improved header-level aware extraction.
        
        Strategies:
        1. Find section start matching header (e.g. "## Method" or "3. Method")
        2. Identify header level (e.g. ## is level 2)
        3. Capture content until next header of SAME or HIGHER importance (level <= current)
        4. For special sections (Experiments/Results), capture until end of doc
        """
        extracted = []
        run_to_end_keywords = ["experiment", "result", "empirical", "evaluation"]
        
        for section in section_names:
            # Clean section name: remove leading numbers/dots
            clean_section = re.sub(r'^[\d\s\.]+', '', section).strip()
            if not clean_section:
                continue
                
            # Regex to find header line
            # Captures: 1=hashes, 2=numbering, 3=title
            # Matches: "^## 3. Method..." or "^3. Method..." (relaxed)
            header_pattern = rf'(?:^|\n)(#+)?\s*(\d+\.?\s*)?({re.escape(clean_section)}[^\n]*)'
            
            # Find all matches
            matches = list(re.finditer(header_pattern, content, re.IGNORECASE))
            if not matches:
                # Try fallback: just the clean section name as a line
                fallback_pattern = rf'(?:^|\n)(#+)?\s*({re.escape(clean_section)}[^\n]*)'
                matches = list(re.finditer(fallback_pattern, content, re.IGNORECASE))
            
            if not matches:
                if self.verbose:
                    console.print(f"[dim]  ⚠ Section '{section}' not found[/dim]")
                continue
                
            # Use the first valid match
            match = matches[0]
            start_index = match.start()
            
            # Determine header level
            hashes = match.group(1)
            if hashes:
                level = len(hashes)
            else:
                # If no hashes, heuristic: 
                # If numbering "X." exists, treat as likely level 2 (assuming top is Title)
                # Or default to 2
                level = 2 
            
            # Check if this is a "run to end" section
            is_run_to_end = any(k in clean_section.lower() for k in run_to_end_keywords)
            
            if is_run_to_end:
                extracted_text = content[start_index:].strip()
                extracted.append(extracted_text)
                if self.verbose:
                    console.print(f"[dim]  Extracted '{clean_section}' (run-to-end): {len(extracted_text)} chars[/dim]")
                continue
            
            # Find next header of same or higher importance (length of hashes <= level)
            # We search from the end of the current match
            search_start = match.end()
            
            # Pattern for next boundary:
            # Matches lines starting with #..# where count <= level
            # OR lines that look like top-level numbered sections if we started with one
            
            next_header_match = None
            
            # Look for markdown headers
            # Construct a regex for headers with 1 to level hashes
            # e.g. if level=2, match # or ##
            next_md_pattern = re.compile(rf'(?:^|\n)#{{1,{level}}}\s')
            next_header_match = next_md_pattern.search(content, search_start)
            
            if next_header_match:
                end_index = next_header_match.start()
                extracted_text = content[start_index:end_index].strip()
            else:
                # No boundary found, take rest
                extracted_text = content[start_index:].strip()
                
            extracted.append(extracted_text)
            if self.verbose:
                 console.print(f"[dim]  Extracted '{clean_section}' (Level {level}): {len(extracted_text)} chars[/dim]")
        
        if extracted:
            return "\n\n---\n\n".join(extracted)
            
        return ""
    
    def _format_figure_list(self, images: List[Any]) -> str:
        """Format list of available figures."""
        if not images:
            return "No figures available"
        
        lines = ["Available figures:"]
        for img in images:
            if hasattr(img, 'image_id'):
                caption = getattr(img, 'caption', '') or img.image_id
                lines.append(f"- {img.image_id}: {caption}")
            elif isinstance(img, dict):
                lines.append(f"- {img.get('id', 'unknown')}: {img.get('caption', '')}")
            else:
                lines.append(f"- {img}")
        
        return "\n".join(lines)
    
    def _format_figure_list_from_index(self, figure_index_path: Path) -> str:
        """
        Load and format figure list from figure_index.json.
        Provides detailed figure descriptions for agent use.
        """
        if not figure_index_path or not figure_index_path.exists():
            return "No figure index available"
        
        try:
            with open(figure_index_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            figures = data.get("figures", [])
            if not figures:
                return "No figures available"
            
            lines = [
                "## Available Figures",
                f"Total: {len(figures)} figures extracted from the paper.",
                "",
                "Use these figure IDs when referencing images in the report:",
                ""
            ]
            
            for fig in figures:
                fig_id = fig.get("id", "unknown")
                page = fig.get("page", "?")
                caption = fig.get("caption", "No caption")
                
                lines.append(f"### {fig_id}")
                lines.append(f"- **Page**: {page}")
                lines.append(f"- **Description**: {caption}")
                lines.append("")
            
            lines.append("---")
            lines.append("When inserting figures, use: <INSERT_FIGURE: Figure_X - reason for inclusion>")
            
            return "\n".join(lines)
            
        except Exception as e:
            console.print(f"[yellow]⚠ Could not load figure index: {e}[/yellow]")
            return "Error loading figure index"

    def _extract_figure_suggestions(self, report: str) -> Dict[str, str]:
        """Extract figure insertion points from report."""
        suggestions = {}
        
        pattern = r'<INSERT_FIGURE:\s*([^>]+)>'
        for match in re.finditer(pattern, report):
            content = match.group(1).strip()
            parts = content.split(' - ', 1)
            fig_id = parts[0].strip()
            desc = parts[1].strip() if len(parts) > 1 else ""
            suggestions[fig_id] = desc
        
        return suggestions
    
    def _extract_variable_tracking(self, math_report: str) -> Optional['VariableTracking']:
        """
        Extract variable tracking information from math specialist report.
        
        Parses the "Complete Variable Tracking Table" section and dependency graph.
        """
        if not math_report:
            return None
        
        tracking = VariableTracking()
        
        # Extract the variable tracking table section
        # Pattern: ### 📊 Complete Variable Tracking Table ... until next ### or end
        table_pattern = r'### 📊 Complete Variable Tracking Table\s*\n(.*?)(?=\n###|\n##|\Z)'
        table_match = re.search(table_pattern, math_report, re.DOTALL)
        
        if table_match:
            tracking.raw_section = table_match.group(0)
            table_content = table_match.group(1)
            
            # Parse markdown table rows
            # | Symbol | Name | Definition | First Appearance | Typical Value | Dependencies |
            row_pattern = r'\|\s*\$?([^$|]*)\$?\s*\|\s*([^|]*)\|\s*([^|]*)\|\s*([^|]*)\|\s*([^|]*)\|\s*([^|]*)\|'
            rows = re.findall(row_pattern, table_content)
            
            for row in rows:
                # Skip header and separator rows
                if row[0].strip().startswith('-') or row[0].strip().lower() == 'symbol':
                    continue
                
                var = {
                    'symbol': row[0].strip(),
                    'name': row[1].strip(),
                    'definition': row[2].strip(),
                    'location': row[3].strip(),
                    'value': row[4].strip(),
                    'dependencies': row[5].strip()
                }
                if var['symbol']:  # Only add if symbol is not empty
                    tracking.variables.append(var)
        
        # Extract dependency graph section
        graph_pattern = r'### 🔗 Variable Dependency Graph\s*\n```(?:[^\n]*)?\n(.*?)```'
        graph_match = re.search(graph_pattern, math_report, re.DOTALL)
        
        if graph_match:
            tracking.dependency_graph = graph_match.group(1).strip()
        else:
            # Try alternative format (text description)
            graph_pattern2 = r'### 🔗 Variable Dependency Graph\s*\n(.*?)(?=\n###|\n##|\Z)'
            graph_match2 = re.search(graph_pattern2, math_report, re.DOTALL)
            if graph_match2:
                tracking.dependency_graph = graph_match2.group(1).strip()
        
        return tracking if tracking.variables or tracking.dependency_graph else None
    
    def _extract_reproduction_checklist(self, experiment_report: str) -> Optional['ReproductionChecklist']:
        """
        Extract reproduction checklist from data auditor report.
        
        Parses datasets, hyperparameters, hardware, code availability, and risk assessment.
        """
        if not experiment_report:
            return None
        
        checklist = ReproductionChecklist()
        
        # Extract the reproduction checklist section
        checklist_pattern = r'### 🔧 Reproduction Checklist\s*\n(.*?)(?=\n### ⚠️ Potential Concerns|\n##|\Z)'
        checklist_match = re.search(checklist_pattern, experiment_report, re.DOTALL)
        
        if checklist_match:
            checklist.raw_section = checklist_match.group(0)
            content = checklist_match.group(1)
            
            # Extract datasets
            checklist.datasets = self._parse_checklist_table(content, '📦 Datasets Required')
            
            # Extract hyperparameters
            checklist.hyperparameters = self._parse_checklist_table(content, '⚙️ Hyperparameters')
            
            # Extract hardware
            checklist.hardware = self._parse_checklist_table(content, '💻 Hardware Requirements')
            
            # Extract code availability
            checklist.code_availability = self._parse_code_availability(content)
            
            # Extract risk assessment
            checklist.risk_assessment = self._parse_checklist_table(content, '⚠️ Reproduction Risk Assessment')
        
        return checklist if (checklist.datasets or checklist.hyperparameters or 
                            checklist.hardware or checklist.risk_assessment) else None
    
    def _parse_checklist_table(self, content: str, section_title: str) -> List[Dict]:
        """Parse a markdown table from a specific section of the checklist."""
        results = []
        
        # Find the section
        section_pattern = rf'#### {re.escape(section_title)}\s*\n(.*?)(?=\n####|\n###|\Z)'
        section_match = re.search(section_pattern, content, re.DOTALL)
        
        if not section_match:
            return results
        
        section_content = section_match.group(1)
        
        # Parse table rows
        lines = section_content.strip().split('\n')
        headers = []
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('---'):
                continue
            
            # Check if it's a header row
            if line.startswith('|') and not headers:
                headers = [h.strip() for h in line.split('|')[1:-1]]
                continue
            
            # Parse data row
            if line.startswith('|') and headers:
                cells = [c.strip() for c in line.split('|')[1:-1]]
                if cells and not all(c.startswith('-') for c in cells):
                    row_dict = {}
                    for i, header in enumerate(headers):
                        if i < len(cells):
                            row_dict[header.lower().replace(' ', '_')] = cells[i]
                    if row_dict:
                        results.append(row_dict)
        
        return results
    
    def _parse_code_availability(self, content: str) -> Dict:
        """Parse code availability section."""
        result = {}
        
        section_pattern = r'#### 🔗 Code Availability\s*\n(.*?)(?=\n####|\n###|\Z)'
        section_match = re.search(section_pattern, content, re.DOTALL)
        
        if section_match:
            section_content = section_match.group(1)
            
            # Parse table
            lines = section_content.strip().split('\n')
            for line in lines:
                line = line.strip()
                if not line or line.startswith('|') and '---' in line:
                    continue
                if line.startswith('|'):
                    cells = [c.strip() for c in line.split('|')[1:-1]]
                    if len(cells) >= 2 and not cells[0].startswith('-'):
                        key = cells[0].lower().replace(' ', '_')
                        status = cells[1] if len(cells) > 1 else ''
                        link = cells[2] if len(cells) > 2 else ''
                        result[key] = {'status': status, 'link': link}
        
        return result


# Convenience function for simple usage
def analyze_paper_hierarchical(
    content: str,
    title: str = "",
    provider: str = "deepseek",
    model: str = "deepseek-chat",
    api_key: str = None,
    images: List = None
) -> HierarchicalAnalysisResult:
    """
    Convenience function for hierarchical paper analysis.
    
    Args:
        content: Paper markdown content
        title: Paper title
        provider: LLM provider
        model: Model name
        api_key: API key
        images: List of extracted images
        
    Returns:
        HierarchicalAnalysisResult
    """
    orchestrator = HierarchicalOrchestrator(
        provider=provider,
        model=model,
        api_key=api_key
    )
    
    return orchestrator.analyze_paper(
        content=content,
        title=title,
        images=images
    )
